default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: todos_dev

test:
  <<: *default
  database: todos_test

production:
  <<: *default
  database: todos
